### ISSUE TITLE
pip install SGTpy

### ISSUE THREAD

**Issue by branch171** [gustavochm/SGTPy#1]
Hi I'm on ubuntu and have python3 installed. I can't run the pip install it gets an error when it trys to run the setup.py file. Its a command error. Any idea on how to get around this.

**Comment by branch171** [comment]
Also I get the same error with phasepy

**Comment by branch171** [comment]
here the error

Running setup.py install for phasepy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools

**Comment by gustavochm** [comment]
Hi!

Could you please check if you have installed SGTPy/Phasepy prerequisites.
These include: numpy, scipy, pandas, setuptools, cython. You can install these with the following command:

`pip3 install numpy scipy pandas setuptools cython`

Additionally, to compile the C part of the package you will need an C/C++ compiler. You can get on ubuntu with the following command:

`sudo apt install build-essential`

Please, let me know if you still got the error after installing the prerequisites.

Gustavo

**Comment by branch171** [comment]
Thanks that works great. I install phasepy then SGTpy. both now say successfully installed

**Comment by gustavochm** [comment]
Great

**Comment by ImagineBaggins** [comment]
Sorry to revive this old thread, but it felt better than starting a new one about the same topic.

I am unable to install sgtpy via pip on Windows 10 (19045). I'm a little hesitant to ask here since it's not immediately clear what is causing the issue, but I can install any other packages via pip just fine.

The pip command "Getting requirements to build wheel" is failing. Below is the traceback of the err:

```
File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-nq9gcd_m\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-nq9gcd_m\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-nq9gcd_m\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-nq9gcd_m\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 36, in <module>
      NameError: name 'build_ext' is not defined
```

Presumably this is referencing `build_ext` of Cython/setuptools, but when I try to run `from Cython.Distutils import build_ext` from near the top of `setup.py` separately in a REPL, I get no error. I also debugged `setup.py` and found that at least in that instance, Cython _is_ being detected. I've checked and updated every single dependency of sgtpy, I've removed all but the latest version of Python (3.11.3) from my machine, and I've verified Python is in the System PATH, so I really don't know what is happening. From the limited info here, it seems like pip is somehow not seeing Cython/setuptools??

I _was_ able to manually install sgtpy from the egg by running the commands `install`, `build`, `install_lib`, `build_py`, `build_ext` on `setup.py` (which I believe is what pip does), and somehow _that_ works, though it does give me deprecation warnings for installing via egg.

---

Another unrelated issue I had to solve before getting sgtpy to work is changing two references in `\sgtpy\sgt\path_sk.py` from `cumtrapz` to `cumulative_trapezoid`. Apparently this is [a new change](https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations) in scipy 1.41.0. Honestly, thank goodness. That former name was... _confusing_ to say the least.

**Comment by gustavochm** [comment]
Hi [ImagineBaggins](https://github.com/ImagineBaggins),

Thank you raising this issue. 

I don't think you are doing anything wrong, but I have been having issues compiling the cython bit on Python 3.10+. I have been mainly using Python 3.9 for that reason. Is it possible to create a conda environment (or any other environment you like) with Python 3.9 and see if you can install without any issue? I have uploaded precompiled wheels to PyPI for python 3.6, 3.7, 3.8 and 3.9, so it should just get one of those.

Thank you for letting me know about the change in the `cumtrapz` function! I have updated it and I'll the push the changes in the next version.

Regards,
Gustavo
